### ISSUE TITLE
Инструмент ввода\редактирования геометрий путем ввода координат вертексов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NextGIS_QGIS_open#10]
Необходимо вводить новые геометрии (точки) путем ввода координат в WGS84.
Исходный слой и проект в 3857, поэтому NumericalDigitize не может быть использован в текущем виде. 
Предлагается либо дописать его, с возможностью выбора WGS84(либо любой другой проекции),
либо написать свой (зачем?).
После добавления геометрии необходимо вызывать форму созданного объекта (стандартное поведение кугиса).
В последующем предполагается улучшить его, добавив умный парсинг координат (различные варианты написания - dd.dddd, gg.mm.ss, ddddd NW, и тд).

**Comment by alisovenko** [comment]
Дорабатываю NumericalDigitize.

**Comment by alexbruy** [comment]
Вообще-то несколько лет назад подобная доработка (в части поддержки разных СК) уже была выполнена.

**Comment by drnextgis** [comment]
Насколько я понял данный плагин позволяет выбрать СК слоя или проекта, а если они оба (и проект и слой, например, в 3857), то с его помощью никак не ввести координаты в 4326.

**Comment by yellow-sky** [comment]
@alexbruy а как можно эту доработку пощупать?

**Comment by alexbruy** [comment]
Лучше у Максима спрашивать, по его просьбе дорабатывалось. Может, где-то и завалялся плагин. У меня точно нет, не храню подобные «мусорные» вещи долго.

**Comment by simgislab** [comment]
@alisovenko сделал необходимый патч с ним и нужно работать, к чему откапывать стюардессу, много лет прошло.

**Comment by simgislab** [comment]
Новый модуль NumericDigitize_NG доступен в нашем публичном репозитории.

@yellow-sky просьба протестировать и закрыть тикет, если задачу решает.

Про умный парсинг плиз вынеси в новый тикет.

**Comment by yellow-sky** [comment]
А где репозиторий этого плагина?

**Comment by simgislab** [comment]
наш публичный

**Comment by yellow-sky** [comment]
Нет, для кода? Куда писать баги и энхансменты?

2015-03-27 9:45 GMT+03:00 Maxim Dubinin <notifications@github.com>:

> наш публичный
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/10#issuecomment-86843409>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by simgislab** [comment]
@alisovenko Седрик не ответил? Если нет - залей текущее состояние сюда, пожалуйста https://github.com/nextgis/NumericDigitize_NG

**Comment by alisovenko** [comment]
Я с ним так и не смог связаться - его почта недоступна.
Можно еще попробовать через http://sourceforge.net/u/cmoe/profile/ - там вроде зарегистрированному пользователю можно сообщения отправлять, но у меня там аккаунта нет, может у кого-то в nextgis есть?

**Comment by alisovenko** [comment]
Отменяю последний комментарий =) Александр Бруй с ним связался. Я еще раз попробую патч отправить.

**Comment by alexbruy** [comment]
У меня SF есть

**Comment by simgislab** [comment]
@alisovenko наверное стоит все равно залить наш код в репозиторий, хуже не будет

**Comment by alisovenko** [comment]
Хорошо

**Comment by alisovenko** [comment]
Сделал
