### ISSUE TITLE
Нет инструментов Saga после установки, хотя они включены

### ISSUE THREAD

**Issue by simgislab** [nextgis/NextGIS_QGIS_open#17]
> При установке NextGIS QGIS на WIN8 предлагается выбрать дополнительные компоненты: Saga, Grass и проч. По умолчанию выбрано всё. Так и оставила. После установки при открытии программы возникает сообщение об ошибке установки, потом исчезает и все норм открывается. Но инструментов Saga там нет, хотя и стоит галочка, что она активирована. И в папке установки тоже есть.

>Переустанавливала 2 раза. Одно и тоже.

>NextGIS QGIS 2.8.1 (bld.31)

http://gis-lab.info/forum/viewtopic.php?f=35&t=18837

**Comment by BishopGIS** [comment]
Да, в Даурском тоже самое было. Ставили сагу отдельно и вручную прописывали пути. Еще там была проблема с путем для temp - он там для саги в пользовательскую директорию прописывается, и если пользователь назван по-русски, то не работает. Возможно ошибка для всего геопроцессинга

**Comment by seevgenia** [comment]
Мой коммент. Максим, спасибо, что переместил сюда. Пользователь у меня на латинице.

**Comment by alisovenko** [comment]
Нужно проверить последний, на данный момент, инсталятор:
nextgis.ru/programs/qgis/ngq-builds/nextgis-qgis-setup-15.4.84.exe

На Win Vista и Win 7  инструменты Saga присутствуют.

**Comment by simgislab** [comment]
да, все ок, причем довольно давно уже, не только в последней версии

![](http://m-d.me/img/ss/20150819-f20-189kb.jpg)
