### ISSUE TITLE
Не работает создание shp-файлов

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NextGIS_QGIS_open#22]
В сборках NGQ (офф и компьюлинк) невозможно создать shp-file.

Судя по всему не работает ogr2ogr. 

ogr2ogr output.shp input.shp выдает пустой shp-file.

Предположительно - ошибка сборки gdal.

Проверено на 2.9.0.79 (тимвьювер можно попросить у @Kinda-me)

**Comment by alisovenko** [comment]
Как ошибку воспроизвести?

**Comment by yellow-sky** [comment]
Заметка: шейп создается, но кривой, не редактируемый. После создания его невозможно редактировать.
Добавить дополнительный атрибут нельзя.

**Comment by alisovenko** [comment]
ogr2ogr output.shp input.shp - gdal работоспособен проверили!

Функционал: "Меню QGIS - Слой" - "Создать Слой" - "создать Шейп-файл"
Вот так QGIS ругается:
"Shape-файлы без атрибутов могут быть открыты только для чтения"

Возможно проблема в qgis при создании shape файла.
Проверяю.

**Comment by simgislab** [comment]
Имей в виду, что у меня при этом та же самая сборка (future-79) работает абсолютно нормально, шейп-файлы редактируются штатно.

**Comment by alisovenko** [comment]
Все будет работать если поставить при создании shape файла кодировку UTF-8.

**Comment by alisovenko** [comment]
Причина в GDAL, наверно в нашем.
При создании слоя с кодировкой LDID/0 ( System в qgis) - gdal выдает ошибку.

**Comment by BishopGIS** [comment]
LDID/87 - это системная кодировка

**Comment by alisovenko** [comment]
Да у меня gdal и с LDID/87 не хочет работать...

**Comment by alisovenko** [comment]
Это у меня gdal без поддержки iconv собран.
Вот причина наверно. Буду пересобирать.

**Comment by yellow-sky** [comment]
Предлагаю поставить цель - собирать с теме же флагами и параметрами, с
которыми собирается "стандартный" OSGEO инсталятор, плюс наши добавки
конечно.
И потихоньку идти к этой цели - что бы наша сборка гдал была не скромнее
стандартной.


31 марта 2015 г., 16:34 пользователь alisovenko <notifications@github.com>
написал:

> Это у меня gdal без поддержки iconv собран.
> Вот причина наверно. Буду пересобирать.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/22#issuecomment-88087357>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by BishopGIS** [comment]
Да, очень похоже на iconv - у меня кстати к нему cmake тоже есть

**Comment by alisovenko** [comment]
Ошибка вызвана тем, что qgis просит gdal сохранить dbf в кодировке LDID/0 (если в диалоге выбрано "System"). 
Наш gdal эту операцию выполнить не может ни с LDID/0, ни с LDID/87.

**Comment by alisovenko** [comment]
Проблему устранили в gdal
