### ISSUE TITLE
Ошибочное значение в wkbType

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NextGIS_QGIS_open#27]
Для некоторых типов слоев (например KMZ) метод  iface.activeLayer().wkbType() возвращает отрицательное значение: -2147483646 (явное переполнение)
Скорее всего это происходит из-за того что в sip биндинге не прописан long тип для enum и не заданы переопределенные значения для отдельных элементов enum.

**Comment by alisovenko** [comment]
Пока есть такая информация:

Такое значение возвращает GDAL метод OGR_G_GetGeometryType, котороый вызывается в qgis тут:
QgsOgrProvider::getOgrGeomType

т.ч., возможно, это все-таки gdal

**Comment by yellow-sky** [comment]
а такой ошибки нет в трекере gdal?

10 апреля 2015 г., 12:04 пользователь alisovenko <notifications@github.com>
написал:

> Пока есть такая информация:
>
> Такое значение возвращает GDAL метод OGR_G_GetGeometryType, котороый
> вызывается в qgis тут:
> QgsOgrProvider::getOgrGeomType
>
> т.ч., возможно, это все-таки gdal
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/27#issuecomment-91485516>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by alisovenko** [comment]
не нашел я такую ошибку в трекере

10 апреля 2015 г., 13:16 пользователь Evgeniy Nikulin <
notifications@github.com> написал:

**Comment by BishopGIS** [comment]
Это не ошибка. Денис пробовал завести тикет, который Иван быстро прибил.
Пример значения правильный.
10 апр. 2015 г. 13:27 пользователь "alisovenko" <notifications@github.com>
написал:

**Comment by yellow-sky** [comment]
GDAL возвращает правильный результат?
То есть в GDAL где то есть отрицательные константы?

10 апреля 2015 г., 13:47 пользователь Dmitry Baryshnikov <
notifications@github.com> написал:

> Это не ошибка. Денис пробовал завести тикет, который Иван быстро прибил.
> Пример значения правильный.
> 10 апр. 2015 г. 13:27 пользователь "alisovenko" <notifications@github.com>
>
> написал:
>
> > не нашел я такую ошибку в трекере
> >
> > 10 апреля 2015 г., 13:16 пользователь Evgeniy Nikulin <
> > notifications@github.com> написал:
> >
> > > а такой ошибки нет в трекере gdal?
> > >
> > > 10 апреля 2015 г., 12:04 пользователь alisovenko <
> > notifications@github.com>
> > >
> > > написал:
> > >
> > > > Пока есть такая информация:
> > > >
> > > > Такое значение возвращает GDAL метод OGR_G_GetGeometryType, котороый
> > > > вызывается в qgis тут:
> > > > QgsOgrProvider::getOgrGeomType
> > > >
> > > > т.ч., возможно, это все-таки gdal
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/nextgis/NextGIS_QGIS_open/issues/27#issuecomment-91485516>
>
> >
> > >
> > > > .
> > > >
> > >
> > >
> > >
> > > --
> > >
> > > Best regards,
> > >
> > > Nikulin Eugeny
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/nextgis/NextGIS_QGIS_open/issues/27#issuecomment-91489608>
>
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/nextgis/NextGIS_QGIS_open/issues/27#issuecomment-91508367>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/27#issuecomment-91513441>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by alisovenko** [comment]
Точно =)
Это геометрия wkbLineString25D

10 апреля 2015 г., 14:47 пользователь Dmitry Baryshnikov <
notifications@github.com> написал:

**Comment by yellow-sky** [comment]
Можеш ссылку дать на код?
Если константа есть, то проблема в коде кугис? или её нет? )) Я уже запутался )

**Comment by alisovenko** [comment]
в ogr_core.h есть константа wkbLineString25D -
http://qgis.org/api/qgis_8h_source.html

10 апреля 2015 г., 15:01 пользователь Evgeniy Nikulin <
notifications@github.com> написал:

**Comment by alisovenko** [comment]
В python API:

qgis.core.QGis.WKBLineString25D

10 апреля 2015 г., 15:18 пользователь Alexander Lisovenko <
alexander.lisovenko@gmail.com> написал:

**Comment by BishopGIS** [comment]
http://trac.osgeo.org/gdal/ticket/5847

**Comment by yellow-sky** [comment]
Да. Это не бег. Оказывается это такой оригинальный стиль задавать перечисление через переполнение.

**Comment by alisovenko** [comment]
Ну это не переполнение, это нумерация с конца, с самого маленького signed int  (–2147483648).
Но, наверно, да - оригинально =)

**Comment by yellow-sky** [comment]
Не знаю как в GDAL, но в QGIS именно переполнением:

http://qgis.org/api/qgis_8h_source.html  63 строка

10 апреля 2015 г., 16:11 пользователь alisovenko <notifications@github.com>
написал:

> Ну это не переполнение, это нумерация с конца, с самого маленького signed
> int (–2147483648).
> Но, наверно, да - оригинально =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/27#issuecomment-91552165>
> .
>



-- 

Best regards,

Nikulin Eugeny
