### ISSUE TITLE
Не выбираются поля при join-е

### ISSUE THREAD

**Issue by drnextgis** [nextgis/NextGIS_QGIS_open#31]
1. Открываем какой-нибудь shape-файл и csv;
2. Заходим в настройки слоя на базе shape-файла: `Properties` - `Joins` - `+`. В поле  `Join layer` автоматом подставляется имя слоя на базе csv-файла, однако при попытке выбрать `Join field` ничего не происходит. Чтобы заработало приходится перевыбирать слой в поле `Join layer`.

**Comment by BishopGIS** [comment]
У меня не воспроизводится

**Comment by drnextgis** [comment]
Я на 2.9.0-Master Ubuntu 14.04

**Comment by simgislab** [comment]
Денис, а причем тут наш кугис?

**Comment by drnextgis** [comment]
Так вроде же договаривались сюда баги постить?

**Comment by drnextgis** [comment]
Исправлено в https://github.com/qgis/QGIS/commit/7aa72ab92488e9262dbba23614ca6d68bd2535f3
