### ISSUE TITLE
Из названия ушло слово qgis. Привычный поиск не работает.

### ISSUE THREAD

**Issue by seevgenia** [nextgis/NextGIS_QGIS_open#34]
Из названия новой версии ушло слово qgis, хотя по сути qgis-ом и является. Не очень удобно при поиске программы. Но если так и задумано специально, вопрос снимается.

**Comment by simgislab** [comment]
@alisovenko давай вернем вместо NGQ -> NextGIS QGIS в названии ярлыка
http://m-d.me/img/ss/20154713-184721.png

**Comment by alisovenko** [comment]
Хорошо.  Название самого инсталлятора (ngq-15.3.exe) оставить или тоже сменить?
Только это изменение попадет уже в версию 15.4.
После этого изменения мы сразу выпускаем новый релиз ngq-15.4? и выкладываем новый общедоступный инсталлятор на сайт?

**Comment by simgislab** [comment]
да, инсталлятор пожалуй можно тоже подлиннее назвать

новый общедоступный релиз пока выпускать не надо, улучшение пока будет только для тех кто с поддержкой

**Comment by alisovenko** [comment]
Сделано. Версия 15.4.31 доступно на сайте.
