### ISSUE TITLE
Изменить ссылку на страничку Коммерческой поддержки

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NextGIS_QGIS_open#35]
В данный момент пункт меню  Справка->Нужна комм поддержка открывает страничку:
http://qgis.org/en/site/forusers/commercial_support.html

а должен:
http://nextgis.ru/services/support/

**Comment by RuslanKiselev** [comment]
+1

**Comment by alisovenko** [comment]
Сделано начиная со сборки 51

**Comment by simgislab** [comment]
Ссылка должна зависеть от текущего языка кугиса. Сейчас из EN версии открывается все равно РУ-ссылка

**Comment by alisovenko** [comment]
Сделано, начиная с nextgis-qgis-setup-15.4.68.exe
