### ISSUE TITLE
Выбор программы по умолчанию

### ISSUE THREAD

**Issue by RuslanKiselev** [nextgis/NextGIS_QGIS_open#38]
Сейчас в винде нельзя выбрать программы по умолчанию из списка вручную для открытия проекта.

**Comment by simgislab** [comment]
по идее ассоциация QGS файлов с нашими бинарниками должна устанавливаться автоматически при установке

**Comment by RuslanKiselev** [comment]
На ноутах в заповеднике ассоциация не происходила. На одном из них иконка проекта отображалась значком pdf файла

**Comment by simgislab** [comment]
о том и речь, что не происходит, но должна

нужно доработать инсталлятор

**Comment by alisovenko** [comment]
На данный момент у меня такие соображения:

Несколько наших инсталяторов могут могут быть установлены на одном ПК одновременно.

Получается несколько вариантов выполнения ассоциации файлов .qgs:
1. При установке как нашего NGQ или производного от нашего NGQ (Compulink, Rekod и др.) Просто связываем файлы .qgs с только, что установленным NGQ. При этом после удаления NGQ удаляется и связь.
Замечания: 
* Например, на ПК уже установлен NGQ и мы хотим установить еще NGQ-Compulink. При установке связываем файл .qgs с NGQ-Compulink. Открывая .qgs  - открывается NGQ-Compulink всегда. Если Мы удаляем NGQ-Compulink - то связь .qgs с NGQ не восстанавливается.

1.2 При установке можно спрашивать: "связать файлы .qgs с устанавливаемой NGQ?"

2. Можно создать умный механизм распознавания связи .qgs с NGQ в инсталяторе. При удалении NGQ будет определяться связана ли эта программа с .qgs и удалять эту связь. При этом восстанавливая связь с другим NGQ, установленном на ПК. - по трудозатратам будет больше и на данный момент я не уверен на 100% что это можно реализовать.

3. Написать отдельную программу связывания .qgs и NGQ. Она будет находиться в  Меню программ вместе с ярлыком запуска NGQ, и устанавливать связь с .qgs

4. Сделать инструкцию и поместить в меню Помощь NGQ, где описать инструкцию связывания .qgs и NGQ - практически ничего делать не нужно =)


Самым лучшим вариантом считаю реализацию 1 и 3 одновременно.

**Comment by simgislab** [comment]
Я думаю, что нужно идти поэтапно. И на первом этапе нужно сделать так, чтобы последний наш инсталлер тупо переписывал на себя ассоциацию. Потому что: 1) по идее обычному юзеру нужен только один инсталлятор, 2) это правильно если он ставит наш кугис, что бы он и открывал проекты

В будущем будем делать и запрос на ассоциацию и распознавание как в 1.2.1, но это все потом.

**Comment by alisovenko** [comment]
Нужна новая иконка для для .qgs файлов?

Или используем ту же, что на на ярлыке : 
https://github.com/nextgis/corp/blob/master/logo/NGQGIS_logo.svg

Или такую: 
https://github.com/nextgis/NextGIS-QGIS/blob/ngq-15_0/images/icons/qgis-mime-icon.png

**Comment by simgislab** [comment]
первая (наша) - хороший вариант

**Comment by alisovenko** [comment]
Сделано начиная со сборки 51

**Comment by simgislab** [comment]
@RuslanKiselev проверь плиз на новой сборке

**Comment by RuslanKiselev** [comment]
максим, проверил, работает!


06.06.2015 13:54, Maxim Dubinin пишет:
>
> @RuslanKiselev <https://github.com/RuslanKiselev> проверь плиз на 
> новой сборке
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/38#issuecomment-109564410>.
>

-- 
С уважением,
Руслан Киселев
NextGIS, nextgis.ru
+79154114241

**Comment by simgislab** [comment]
у меня тоже все красиво
