### ISSUE TITLE
Версия в заголовке должна быть полной

### ISSUE THREAD

**Issue by simgislab** [nextgis/NextGIS_QGIS_open#40]
Сейчас она обрезана по major - 15.4, лучше показывать полностью 15.4.62

То же самое касается окна About, там тоже нет полной версии.

В результате сейчас ее вообще нигде нет.

**Comment by alisovenko** [comment]
А точно нужно?
Согласно https://github.com/nextgis/corp/blob/rfc-nextgis-qgis/rfc/nextgis-qgis.rst мы нумеруем наши версии двухзначным кодами, только их и распространяем. Версии с номером билда, это же должно быть только для нашего внутреннего пользования, для тестов.. и т.п. 
А действительно пользоваться мы должны релизами с двузначными номерами.

А полную версию можно и сейчас посмотреть в Windows в панели управления: "Программы и компоненты" ("Удаление и установка программ").

Сделать это - проблем нет. Точно нужно?

**Comment by simgislab** [comment]
Давай хотя бы в About добавим. 

Но вообще для клиентов мы распространяем и трехзначные же по идее, а там важно что же он себе установил - 52 или 67.

**Comment by alisovenko** [comment]
Сделано, начиная с nextgis-qgis-setup-15.4.67.exe
