### ISSUE TITLE
Некорректная работа инструмента Reshape Features.

### ISSUE THREAD

**Issue by Zeddikus** [nextgis/NextGIS_QGIS_open#45]
Инструмент Reshape Features периодически не работает. Время от времени создаю полигоны, геометрия которых не может быть изменена с помощью инструмента Reshape Features. То есть, я могу начертить линию уточнённых границ полигона, но после завершения ре-шейпинга (нажатия на правую кнопку мыши), ничего не происходит - границы полигона остаются неизменными. Это происходит не всегда и не с каждым полигоном, но очень досадно, когда периодически, после длительной, кропотливой работы по уточнению границы получаешь нулевой результат. Вот пример полигона, границы которого я не могу изменить с помощью инструмента Reshape Features:

https://www.dropbox.com/s/v4gmz889ye4rvyp/bug.zip?dl=0

Глюк воспроизводится на моей Windows машине (Windows 7 Enterprise, 64 bit) в моей установленной версии NextGIS QGIS во вновь созданном пустом проекте. А также в QGIS version 1.8.0-Lisboa, установленной на Red Hat Enterprise Linux 6.

**Comment by simgislab** [comment]
А версия NGQ?

**Comment by Zeddikus** [comment]
QGIS version	1.9.0-Master		QGIS 		code revision				fef6e2b
Compiled against Qt			4.7.1		Running against Qt			4.7.1
Compiled against GDAL/OGR		1.9.2		Running against GDAL/OGR	1.9.2
GEOS Version					3.3.8		PostgreSQL Client Version	8.3.10
SpatiaLite Version				4.1.1		QWT Version				5.2.1
PROJ.4 Version				480			QScintilla2 Version			2.6.2
This copy of QGIS writes debugging output.

**Comment by simgislab** [comment]
для начала нужно обновиться вот отсюда: http://nextgis.ru/nextgis-qgis/

**Comment by Zeddikus** [comment]
В новой версии QGIS (15.4.68) инструмент Reshape Features работает корректно с данным полигоном. Потестирую другие полигоны в процессе работы.

**Comment by simgislab** [comment]
переоткрой если нужно
