### ISSUE TITLE
Не ставится на Win: qgis_fm.qm

### ISSUE THREAD

**Issue by trolleway** [nextgis/NextGIS_QGIS_open#47]
Сборка с nextgis.ru не ставится на windows.
![nextgis-open](https://cloud.githubusercontent.com/assets/4630662/10340775/5fe1279c-6d1a-11e5-880b-e9c4f4ec8871.png)

**Comment by alisovenko** [comment]
Инсалятор nextgis-qgis-setup-15.4.88.exe?
Какая версия Windows?
Место установки оставил по-умолчанию? Сколько места на дисках до установки?
Паралельно что-то еще устанавливалось?

**Comment by trolleway** [comment]
а, стоп, там место кончилось
