### ISSUE TITLE
Неверные координаты курсора в статусе

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/NextGIS_QGIS_open#6]
Если карта в метровой СК, а необходимо видеть градусы, то можно это выставить в свойствах проекта:
Идем в Проекты - Свойства проекта - Единицы карты и ставим там Г-М-С. Сохраняем. Двигаем курсор по карте и видим странные (42°26′50″З,5563379°45′53″С) координаты в статусе. Реально это 117 ВД и 50 СШ

Проверялось на СК EPSG:32650

**Comment by simgislab** [comment]
подтверждаю

![](http://m-d.me/img/ss/20155818-125846.png)

**Comment by drnextgis** [comment]
[#12395](https://hub.qgis.org/issues/12395)

**Comment by drnextgis** [comment]
Исправлено в https://github.com/qgis/QGIS/commit/803a0b9375217671fc625f3156533d693b5d1895
