### ISSUE TITLE
На некоторых компьютерах при идентификации нескольких объектов подряд не снимается выделение

### ISSUE THREAD

**Issue by trolleway** [nextgis/NextGIS_QGIS_open#61]
![image](https://cloud.githubusercontent.com/assets/4630662/12750674/b137d9e0-c9c9-11e5-840c-f6671c9611c6.png)

Как на скриншоте, но если нажать на несколько точек подряд, то красное выделение остается на экране.

**Comment by yellow-sky** [comment]
Открыты формы объектов (отдельные окна). Пока не закроешь эти окна,
выделение останется.

2 февраля 2016 г., 16:28 пользователь Artem Svetlov <
notifications@github.com> написал:

> [image: image]
> <https://cloud.githubusercontent.com/assets/4630662/12750674/b137d9e0-c9c9-11e5-840c-f6671c9611c6.png>
>
> Как на скриншоте, но если нажать на несколько точек подряд, то красное
> выделение остается на экране.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/61>.
>



-- 

Best regards,

Nikulin Eugeny

**Comment by trolleway** [comment]
Задокументировал это явление. https://github.com/nextgis/docs_ngqgis/blob/master/source/vector_op.rst
