### ISSUE TITLE
 Не могу соединиться с NGW  при помощи  плагина Ресурсы NGW

### ISSUE THREAD

**Issue by paleogis** [nextgis/NextGIS_QGIS_open#64]
Пишет ОШИБКА: Ошибка при получении ресурсов: __init__() got an unexpected keyword argument 'json'
Правильность логина и пароля проверил
OS Ubuntu 14.04
![_057](https://cloud.githubusercontent.com/assets/5592860/12872466/333c041e-cdb4-11e5-85ec-8b2cc24398be.png)

Версия QGIS
2.12.3-Lyon
Ревизия
exported
Версия Qt при сборке
4.8.6
Текущая версия Qt
4.8.6
Версия GDAL/OGR при сборке
1.10.1
Текущая версия GDAL/OGR
1.11.2
Версия GEOS при сборке
3.4.2-CAPI-1.8.2
Текущая версия GEOS
3.4.2-CAPI-1.8.2 r3921
Версия PostgreSQL
9.3.4
Версия SpatiaLite
4.1.1
Версия QWT
5.2.3
Версия PROJ.4
480
Версия QScintilla2
2.8.1

**Comment by simgislab** [comment]
речь о плагине NGWConnect? если да, то тикет нужно переоткрыть тут: https://github.com/nextgis/ngw_connect

**Comment by paleogis** [comment]
ок
