### ISSUE TITLE
Инструмент слияния нескольких (>2) слоев в один результирующий

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NextGIS_QGIS_open#8]
Необходим инструмент, аналогичный MergeVectorLayers из стандартного Processing, но с возможностью объединять более двух слоев.

**Comment by BishopGIS** [comment]
А инструмент объединения шейп-файлов?

**Comment by yellow-sky** [comment]
Это не шейп файлы. Это векторные слои в кугисе. Например из gpx файлов.

2015-03-18 20:58 GMT+03:00 Dmitry Baryshnikov <notifications@github.com>:

> А инструмент объединения шейп-файлов?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/8#issuecomment-83097669>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by BishopGIS** [comment]
Как-то не внятно тогда. Слои могут быть readonly. Могут не поддерживать обновление, что делать с разным составом атрибутов, какой слой к какому стыкуется, какой выходной формат и т.д. Было бы неплохо расписать инструмент подробнее с учетом специфики разных слоев.

**Comment by yellow-sky** [comment]
Инструмент уже есть. Все эти вопросы в нем уже решены. Необходимо убрать
ограничение на два слоя.
18.03.2015 21:04 пользователь "Dmitry Baryshnikov" <notifications@github.com>
написал:

**Comment by BishopGIS** [comment]
Не согласен с "плодением" всяких объединяющих инструментов. Надо как-то системно подходить.

**Comment by yellow-sky** [comment]
А в чем тут "плодение"? Инструмент реально существует. Им можно воспользоваться. Но в нем есть ограничение на два слоя. Я предлагаю сделать его более универсальным - убрать ограничение по количеству слоев.

**Comment by simgislab** [comment]
почему не доделать наш плагин Merge Shapes?

**Comment by yellow-sky** [comment]
почему не доделать существующий инструмент в processing? это проще и
быстрее имхо

2015-03-18 22:14 GMT+03:00 Maxim Dubinin <notifications@github.com>:

> почему не доделать наш плагин Merge Shapes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/NextGIS_QGIS_open/issues/8#issuecomment-83125878>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by BishopGIS** [comment]
Меня убедил

**Comment by yellow-sky** [comment]
Лучше дождаться автора. Только он может сказать, что будет проще сделать. Может в геопроцессинге не так просто сделать множественный инпут.

**Comment by yellow-sky** [comment]
Новый инструмент qmerger
