### ISSUE TITLE
Более информативное название слоя при добавлении из форматов gpx, garmin, geojson

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/NextGIS_QGIS_open#9]
При добавлении нескольких слоев gpx в проект получаем, что все добавленные слои имеют названия "waypoints". Это очень неудобно при добавлении большого (>3) количества слоев. Инструмент идентификации так же возвращает название waypoints, и определить в каком слое находится объект невозможно.
Аналогично для остальных форматов.
Предлагается выводить название слоя (название файла без расширения) + тип геометрии (waypoints, tracks/lines и тд)

**Comment by alexbruy** [comment]
А что с растрами, там все в порядке? Думаю, имеет смысл решить проблему комплексно, и для вектора, и для растра (если она там присутствует)

**Comment by simgislab** [comment]
попробовал, растры вроде нормально подгружаются, имя слоя = имени файла

фичреквест поддерживаю, частое мучение

**Comment by alexbruy** [comment]
Обычные нормально отображаются, как и обычные векторы. Я про растры с подслоями, у меня просто под рукой ничего такого нет чтобы проверить

**Comment by simgislab** [comment]
попробовал HDF, в котором может быть много всего, но он у меня, к сожалению не поддерживается самим кугисом.

Вот примеры если у вас кугис их понимает:
* http://gis-lab.info/data/samples/aster-l1a-moscow-hdf.zip
* http://gis-lab.info/data/samples/mod14-1scene.7z

**Comment by alexbruy** [comment]
С растрами такая же ситуация

**Comment by alexbruy** [comment]
Вариант "layerName (sublayerName)" устроит?

**Comment by yellow-sky** [comment]
Думаю да. Хороший вариант
21.03.2015 16:47 пользователь "alexbruy" <notifications@github.com> написал:

**Comment by BishopGIS** [comment]
Мне больше нравится вариант
+ layer name
| - sublayer name 1
| - sublayer name 2

А если подслой всего один, то сразу sublayer name 1
